package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.remoteParameters.hashiCorpVaultParameter
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PublishFile'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PublishFile")) {
    params {
        expect {
            hashiCorpVaultParameter {
                name = "env.AWS_ACCESS_KEY_ID"
                query = "aws/data/access!/AWS_ACCESS_KEY_ID"
                vaultId = "VaultConnection1"
            }
        }
        update {
            hashiCorpVaultParameter {
                name = "env.AWS_ACCESS_KEY_ID"
                query = "aws/data/access!/AWS_ACCESS_KEY_ID"
                vaultId = "VaultConnection1"
                param("buildTypeId", "VaultAndSelectFromDSL_PublishFile")
            }
        }
    }
}
